"""Alembic environment script.

Alembic invokes this module to drive both online (against a live DB) and
offline (script-generating) migrations.  Two notable customisations vs the
out-of-the-box template:

1.  **Database URL comes from `peach.config.settings`** rather than the
    `sqlalchemy.url` key in `alembic.ini`.  This keeps the URL in one place
    (the env-validated pydantic settings) and means migrations work in any
    environment without editing the ini file.

2.  **All ORM models are imported via `peach.db.models`** so that
    `target_metadata = Base.metadata` sees every table.  Forgetting to
    import a model is the #1 source of "Alembic autogenerated an empty
    migration" mistakes.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from peach.config.settings import get_settings
from peach.db.base import Base

# Critical: importing this package registers every ORM class with
# `Base.metadata`.  Without this import, autogenerate produces an empty
# migration even when models exist.
import peach.db.models  # noqa: F401  (intentional side-effect import)


# ---------------------------------------------------------------------------
# Alembic context
# ---------------------------------------------------------------------------
# `context.config` is the parsed alembic.ini.  We mutate one value
# (sqlalchemy.url) at runtime so the rest of Alembic's machinery picks up
# our settings-derived URL.
# ---------------------------------------------------------------------------
config = context.config

# Configure Python logging from alembic.ini's logger sections.  Skipped if
# the file has no [loggers] section (defensive — our file does, but
# upstream defaults are missing it).
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Inject the database URL from pydantic-settings.  This is the single line
# that ties Alembic to our env-based config.
config.set_main_option("sqlalchemy.url", get_settings().database_url)

# `target_metadata` is what autogenerate diffs against the live database
# schema.  Pointing it at our shared `Base.metadata` makes every ORM model
# automatically migration-aware (provided it has been imported above).
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode — emit SQL to stdout.

    Used by:
        alembic upgrade head --sql > migration.sql

    Useful when DBAs require a SQL review before changes hit production.
    Not used in our normal dev loop.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        # `literal_binds=True` inlines parameter values in the generated SQL.
        # Safe in this context because Alembic only generates DDL.
        literal_binds=True,
        # `compare_type=True` makes autogenerate notice column type changes,
        # not just additions/removals.  Catches subtle bugs like changing
        # NUMERIC(18,4) to NUMERIC(20,6).
        compare_type=True,
        # `compare_server_default=True` similarly notices changes to
        # column defaults.
        compare_server_default=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode — apply directly to the configured DB.

    This is the normal path (`alembic upgrade head`).
    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        # NullPool — we don't want Alembic to keep a connection pool alive
        # after the migration finishes.  Each `alembic upgrade` is a
        # one-shot process; a pool would just add shutdown lag.
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=True,
        )

        with context.begin_transaction():
            context.run_migrations()


# Alembic invokes one of the two functions based on whether `--sql` was passed.
if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
